name: Tests

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'src/**'
      - 'test_resources/**'
      - 'Cargo.toml'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'src/**'
      - 'test_resources/**'
      - 'Cargo.toml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Run tests
        run: 'echo "No tests required" '
