name: Crates.io

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - 
      name: Push to Crates.io
      run: cargo publish --token ${CARGO_REGISTRY_TOKEN}
      env:
        CRATES_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
