name: Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'test_resources/**'
      - 'Cargo.toml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'test_resources/**'
      - 'Cargo.toml'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose
